[theme]
primaryColor = "#71797E" # Grigio Argento
backgroundColor = "#F8F9FA" # Bianco sporco/Perla
secondaryBackgroundColor = "#E5E4E2" # Platino
textColor = "#2C3E50" # Blu Notte molto scuro
font = "serif"
